title: Jared Pursiano  # your name (or website title) here
logo: /images/Untitled.png?raw=true # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Bachelors Degree in Business Managment with an emphasis in Operations and Information management from the University of Colorado Boulder. 
  Continued my education in data analytics at CU pursuing a Master's degree in Business Analytics, with an emphasis in Security Analytics. 
  <br>
  This is a portfolio of some of the projects I did to achieve my Masters Degree. 
  <br><br><br>
  <a href="https://www.linkedin.com/in/jared-pursiano">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
